# 所属集群名称
brokerClusterName = DefaultCluster
# Broker名称，注意此处不同的Broker应配置不同的名称
brokerName = broker-a
# Broker ID，0表示Master，大于0表示Slave
brokerId = 0
# 对外暴露的IP地址
brokerIP1 = 202.60.228.31
# 客户端通信端口
listenPort = 10914
# 与NameServer通信端口
namesrvListenPort = 9876
# 存储路径
storePathRootDir = /root/store
storePathCommitLog = /root/store/commitlog
# 配置文件路径
confFile = /root/broker.conf
deleteWhen = 04
fileReservedTime = 48
brokerRole = ASYNC_MASTER
flushDiskType = ASYNC_FLUSH